$(function(){    
    //失去焦点
    $('#city').on('click',function(){
    	$(this).blur();
    });
    $('#get').on('click',function(){
    	$(this).blur();
    });
    //选择
    $('.slt').change(function(){
		$(this).prev('input').val($(this).children('option:selected').val());
	});
});
